id: IE9E97B64
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-17T12:18:06+00:00'
last_modified: '2022-06-15T17:36:40.068677+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG4230
  title: བདེ་མཆོག་ནམ་མཁའ་དང་མཉམ་པའི་རྒྱུད་ཀྱི་རྩ་འགྲེལ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    9B16:
      image_group_id: I1PD97692
      title: Volume 1 of bde mchog nam mkha' dang mnyam pa'i rgyud kyi rtsa 'grel
      total_pages: 68
      order: 1
      base_file: 9B16.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
